JenkinsXGitHub:
  password: ""
  username: ""
certmanager:
  enabled: false
  production: "false"
cluster:
  domain: ""
  exposer: Ingress
  name: ""
  namespace: jx
  namespaceSubDomain: -jx.
  projectID: ""
  serverUrl: ""
  zone: ""
docker-registry:
  enabled: false
gitops:
  dev:
    dockerRegistryOrg: ""
    envOrganisation: ""
    owner: ""
    repo: ""
    server: ""
    scheduler: env-scheduler
  gitKind: github
  gitName: ""
  gitUrlPathPrefix: ""
  gitPublic: false
  owner: ""
  production:
    owner: ""
    repo: ""
    server: ""
    scheduler: env-scheduler
    remote: false
  server: https://github.com
  staging:
    owner: ""
    repo: ""
    server: ""
    scheduler: env-scheduler
    remote: false
  versionStreamRef: ""
  versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webhook: ""
jenkins:
  enabled: false
jenkins-x-platform:
  chartmuseum:
    enabled: true
lighthouse:
  enabled: true
nexus:
  enabled: true
prow:
  enabled: false
storage:
  logs:
    url: ""
  reports:
    url: ""
  repository:
    url: ""
namespace:
  enabled: true
helmMajorVersion: "2"
