{{- if .Values.jenkins.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: jx-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
{{- if .Values.cluster.ingress.annotations }}
{{ toYaml .Values.cluster.ingress.annotations | indent 4 }}
{{- end }}
  name: jenkins
spec:
  rules:
  - host: jenkins{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
{{- if .Values.cluster.tls }}
  tls:
  - hosts:
    - jenkins{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
{{- if eq .Values.certmanager.production "true" }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
