{{- if .Values.bucketrepo.password }}
apiVersion: v1
data:
  BASIC_AUTH_PASS: "{{ .Values.bucketrepo.password | b64enc }}"
  BASIC_AUTH_USER: "{{ .Values.bucketrepo.username | b64enc }}"
kind: Secret
metadata:
  annotations:
    jenkins.io/credentials-keybinding-password: BASIC_AUTH_PASS
    jenkins.io/credentials-keybinding-username: BASIC_AUTH_USER
    jenkins.io/foo: bar
  labels:
    jenkins.io/credentials-type: usernamePassword
    release: jenkins-x
  name: jenkins-x-bucketrepo
type: Opaque
{{- end }}